sonar.organization=huymt05
sonar.projectKey=huymt05_goldenowl-devops-internship-challenge
sonar.sources=src
sonar.tests=src/tests
sonar.exclusions=src/tests/**,src/coverage/**,src/node_modules/**
sonar.javascript.lcov.reportPaths=src/coverage/lcov.info